# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-cd

on:
  push:
    branches: [ main ]

jobs:
  update:

    runs-on: self-hosted

    steps:
    - run: cd /var/www/x3fable
    - run: git pull

  build:

    runs-on: self-hosted
    needs: [update]
    steps:
    - run: cd /var/www/x3fable
    - run: npm i
    - run: npx prisma migrate deploy --schema="/var/www/x3fable/prisma/schema.prisma"
    - run: npm run build

  start:

    runs-on: self-hosted
    needs: [build]
    steps:
    - run: PM2_HOME=/root/.pm2 pm2 restart server
