# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update:

    runs-on: self-hosted
    
    steps:
    - run: cd /var/www/x3fable
    - run: git pull
    
  build:

    runs-on: self-hosted
    
    steps:
    - run: ls
    - run: cd /var/www/x3fable
    - run: npm i
    - run: npm run build
  
  start:
    
    runs-on: self-hosted
    
    steps:
    - run: PM2_HOME=/root/.pm2 pm2 restart server
